export const DELETE_USER = 'DELETE_USER';
export const UPDATE_USER_LIST = 'UPDATE_USER_LIST';
export const SAVING_ERROR = 'SAVING_ERROR';
export const RESET_SAVING_ERROR = 'RESET_SAVING_ERROR';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SAVE_ENTITY = 'SAVE_ENTITY';
export const UPDATE_ENTITIES = 'UPDATE_ENTITIES';
export const ENTITY_LOADING_STATUS = 'ENTITY_LOADING_STATUS';
export const USER_LIST_LOADING_STATUS = 'USER_LIST_LOADING_STATUS';
export const SET_ID_RATING = 'SET_ID_RATING';



