@startmindmap
* Исходные данные
** Составляющая дохода
** Карьерные уровни

/'*** Linux Mint
*** Kubuntu
*** Lubuntu
*** KDE Neon
** LMDE
** SolydXK
** SteamOS
** Raspbian with a very long name
*** <s>Raspmbc</s> => OSMC
*** <s>Raspyfi</s> => Volumio'/
@endmindmap


@startwbs
* Составляющая дохода
** Карьерные уровни
*** Коэффициенты выплаты по уровням
**** Расчет плана
***** Общий план по категорям
****** Уровни выполнения плана
******* Автоматический
******** Условия расчета
******* Индивидуальный
******** Индивидуальный план
******** Условия расчета

@endwbs